# Indentation matters — use spaces, not tabs

# determine year/month
# optional override
# year: 2026
# month: 02

# OR leave blank to auto use previous month
year:
month:

# Folder containing files from Investran
investran_reports_folder: ./reports/investran_reports

# Folder containing bank reports
bank_reports_folder: ./reports/bank_reports

# Output folder for zipped file
output_folder: ./zip_for_bank

# Name of the zip file
zip_name: report_bank.zip

# Files to pick from Investran folder. Lists use -
files_from_investran:
  - bank_recs.xlsx
  - deals.xlsx
  - nav.xlsx

# Extra file from another folder
extra_file: bank_reports.xlsx
