# Indentation matters — use spaces, not tabs

# Folder containing files from Investran
input_folder_a: ../reports/investran_reports

# Folder containing bank reports
input_folder_b: ../reports/bank_reports

# Output folder for zipped file
output_folder: ../zip_for_bank

# Name of the zip file
zip_name: report_bank.zip

# Files to pick from Investran folder. Lists use -
files_from_investran:
  - bank_reports.xlsx
  - deals.xlsx
  - nav.xlsx

# Extra file from another folder
extra_file:
  - bank_reports.xlsx
